import React from 'react';
import {StyleSheet} from 'react-native';
import {Container, Content, View} from '../../../common';
import Text from '../../../common/TextV2';
import {useRoute} from '@react-navigation/native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import Gap from '../../../common/Gap';
import * as Colors from '../../../config/colors';
import Header from '../../component/Header';

/* =============================================================================
<TermCondition />
============================================================================= */
const TermCondition = () => {
  const route = useRoute();
  const insets = useSafeAreaInsets();

  return (
    <Container>
      <Header title={'Term & Condition'} />

      <Content padding={16} style={{marginBottom: insets.bottom}}>
        <Text size="small" color={Colors.black500}>
          This Privacy Policy applies to our app. By accessing or using our
          Service, you signify that you have read, understood, and agree to our
          collection, storage, use, and disclosure of your personal information
          as described in this Privacy Policy and our Terms of Service.
        </Text>
        <Gap height={24} />
        <Text family="semi" size="small">
          Definitions and key terms
        </Text>
        <Gap height={4} />
        <Text size="small" color={Colors.black500}>
          To help explain things as clearly as possible in this Privacy Policy,
          every time any of these terms are referenced, are strictly defined as:
        </Text>
        <Gap height={16} />
        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            Cookie: small amount of data generated by a website and saved by
            your web browser. It is used to identify your browser, provide
            analytics, remember information about you such as your language
            preference or login information.
          </Text>
        </View>

        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            Company: when this policy mentions “Company,” “we,” “us,” or “our,”
            it refers to Termify that is responsible for your information under
            this Privacy Policy.
          </Text>
        </View>

        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            Customer: refers to the company, organization or person that signs
            up to use the Termify Service to manage the relationships with your
            consumers or service users.
          </Text>
        </View>

        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            Device: any internet connected device such as a phone, tablet,
            computer or any other device that can be used to visit Termify and
            use the services. Personal Data: any information that directly,
            indirectly, or in connection with other information — including a
            personal identification number — allows for the identification or
            identifiability of a natural person.
          </Text>
        </View>

        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            Personal Data: any information that directly, indirectly, or in
            connection with other information — including a personal
            identification number — allows for the identification or
            identifiability of a natural person.
          </Text>
        </View>

        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            Service: refers to the service provided by Termify as described in
            the relative terms (if available) and on this platform.
          </Text>
        </View>

        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            Third-party service: refers to advertisers, contest sponsors,
            promotional and marketing partners, and others who provide our
            content or whose products or services we think may interest you.
          </Text>
        </View>

        <View horizontal>
          <View>
            <Text size="small" color={Colors.black500}>
              •
            </Text>
          </View>

          <Text
            size="small"
            color={Colors.black500}
            customStyle={{flex: 1, marginLeft: 8, marginBottom: 4}}>
            You: a person or entity that is registered with Termify to use the
            Services.
          </Text>
        </View>
        <Gap height={16} />

        <Text family="semi" size="small">
          What Information Do We Collect?
        </Text>
        <Gap height={4} />
        <Text size="small" color={Colors.black500}>
          We collect information from you when you visit our website, register
          on our site, place an order, subscribe to our newsletter, respond to a
          survey or fill out a form.
        </Text>
        <Gap height={16} />
        <Text size="small" color={Colors.black500}>
          {`Phone Numbers
Email Addresses
Name / username
Billing Addresses
How Do We Use The Information We Collect?
Any of the information we collect from you may be used in one of the following ways:`}
        </Text>
        <Gap height={16} />
        <Text family="semi" size="small">
          How Long Do We Keep Your Information?
        </Text>
        <Gap height={4} />
        <Text size="small" color={Colors.black500}>
          We keep your information only so long as we need it to provide Termify
          to you and fulfill the purposes described in this policy. This is also
          the case for anyone that we share your information with and who
          carries out services on our behalf. When we no longer need to use your
          information and there is no need for us to keep it to comply with our
          legal or regulatory obligations, we’ll either remove it from our
          systems or depersonalize it so that we can't identify you.
        </Text>
        <Gap height={16} />
        <Text family="semi" size="small">
          How Do We Protect Your Information?
        </Text>
        <Gap height={4} />
        <Text size="small" color={Colors.black500}>
          We implement a variety of security measures to maintain the safety of
          your personal information when you place an order or enter, submit, or
          access your personal information. We offer the use of a secure server.
          All supplied sensitive/credit information is transmitted via Secure
          Socket Layer (SSL) technology and then encrypted into our Payment
          gateway providers database only to be accessible by those authorized
          with special access rights to such systems, and are required to keep
          the information confidential. After a transaction, your private
          information (credit cards, social security numbers, financials, etc.)
          is never kept on file. We cannot, however, ensure or warrant the
          absolute security of any information you transmit to Termify or
          guarantee that your information on the Service may not be accessed,
          disclosed, altered, or destroyed by a breach of any of our physical,
          technical, or managerial safeguards.
        </Text>
      </Content>
    </Container>
  );
};
const styles = StyleSheet.create({
  text: {
    marginHorizontal: 16,
    flex: 1,
  },
});

export default TermCondition;
